import type { Product } from "../types/voice.types"

// Sample Indian grocery products database
export const productDatabase: Product[] = [
  {
    id: "1",
    name: "Basmati Rice",
    brand: "India Gate",
    price: 180,
    category: "Grains & Cereals",
    description: "Premium quality basmati rice",
    location: { aisle: "A1", shelf: "Middle", position: "Center" },
    dietary: ["gluten-free"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "2",
    name: "Organic Milk",
    brand: "Amul",
    price: 60,
    category: "Dairy & Eggs",
    description: "Fresh organic milk",
    location: { aisle: "B2", shelf: "Cold Storage", position: "Front" },
    dietary: ["organic", "high-protein"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "3",
    name: "Whole Wheat Bread",
    brand: "Britannia",
    price: 45,
    category: "Bakery",
    description: "Healthy whole wheat bread",
    location: { aisle: "C1", shelf: "Top", position: "Left" },
    dietary: ["whole-grain", "high-fiber"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "4",
    name: "Bananas",
    brand: "Fresh Farm",
    price: 60,
    category: "Fruits & Vegetables",
    description: "Fresh ripe bananas",
    location: { aisle: "D1", shelf: "Display", position: "Front" },
    dietary: ["organic", "vegan", "gluten-free"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "5",
    name: "Toor Dal",
    brand: "Tata Sampann",
    price: 140,
    category: "Pulses & Legumes",
    description: "Premium quality toor dal",
    location: { aisle: "A2", shelf: "Middle", position: "Center" },
    dietary: ["high-protein", "gluten-free", "vegan"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "6",
    name: "Turmeric Powder",
    brand: "Everest",
    price: 35,
    category: "Spices & Masalas",
    description: "Pure turmeric powder",
    location: { aisle: "E1", shelf: "Top", position: "Right" },
    dietary: ["organic", "gluten-free", "vegan"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "7",
    name: "Green Tea",
    brand: "Tata Tea",
    price: 280,
    category: "Beverages",
    description: "Healthy green tea",
    location: { aisle: "F1", shelf: "Middle", position: "Left" },
    dietary: ["organic", "antioxidant"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "8",
    name: "Almonds",
    brand: "Tulsi",
    price: 450,
    category: "Dry Fruits & Nuts",
    description: "Premium quality almonds",
    location: { aisle: "G1", shelf: "Top", position: "Center" },
    dietary: ["high-protein", "healthy", "gluten-free"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
]

// Categories available
export const categories = [
  "Fruits & Vegetables",
  "Dairy & Eggs",
  "Grains & Cereals",
  "Pulses & Legumes",
  "Spices & Masalas",
  "Beverages",
  "Bakery",
  "Dry Fruits & Nuts",
]

// Dietary options
export const dietaryOptions = [
  "organic",
  "gluten-free",
  "dairy-free",
  "vegan",
  "vegetarian",
  "high-protein",
  "low-fat",
  "whole-grain",
  "high-fiber",
  "healthy",
]
