import type { Product } from "../types/voice.types"

// Sample Indian grocery products database
export const productDatabase: Product[] = [
  {
    id: "1",
    name: "Basmati Rice",
    brand: "India Gate",
    price: 180,
    category: "Grains & Cereals",
    description: "Premium quality basmati rice",
    location: { aisle: "A1", shelf: "Middle", position: "Center" },
    dietary: ["gluten-free"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "2",
    name: "Organic Milk",
    brand: "Amul",
    price: 60,
    category: "Dairy & Eggs",
    description: "Fresh organic milk",
    location: { aisle: "B2", shelf: "Cold Storage", position: "Front" },
    dietary: ["organic", "high-protein"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "3",
    name: "Whole Wheat Bread",
    brand: "Britannia",
    price: 45,
    category: "Bakery",
    description: "Healthy whole wheat bread",
    location: { aisle: "C1", shelf: "Top", position: "Left" },
    dietary: ["whole-grain", "high-fiber"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "4",
    name: "Bananas",
    brand: "Fresh Farm",
    price: 60,
    category: "Fruits & Vegetables",
    description: "Fresh ripe bananas",
    location: { aisle: "D1", shelf: "Display", position: "Front" },
    dietary: ["organic", "vegan", "gluten-free"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "5",
    name: "Toor Dal",
    brand: "Tata Sampann",
    price: 140,
    category: "Pulses & Legumes",
    description: "Premium quality toor dal",
    location: { aisle: "A2", shelf: "Middle", position: "Center" },
    dietary: ["high-protein", "gluten-free", "vegan"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "6",
    name: "Turmeric Powder",
    brand: "Everest",
    price: 35,
    category: "Spices & Masalas",
    description: "Pure turmeric powder",
    location: { aisle: "E1", shelf: "Top", position: "Right" },
    dietary: ["organic", "gluten-free", "vegan"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "7",
    name: "Green Tea",
    brand: "Tata Tea",
    price: 280,
    category: "Beverages",
    description: "Healthy green tea",
    location: { aisle: "F1", shelf: "Middle", position: "Left" },
    dietary: ["organic", "antioxidant"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "8",
    name: "Almonds",
    brand: "Tulsi",
    price: 450,
    category: "Dry Fruits & Nuts",
    description: "Premium quality almonds",
    location: { aisle: "G1", shelf: "Top", position: "Center" },
    dietary: ["high-protein", "healthy", "gluten-free"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "9",
    name: "Organic Brown Bread",
    brand: "Harvest Gold",
    price: 55,
    category: "Bakery",
    description: "Organic whole grain brown bread",
    location: { aisle: "C1", shelf: "Top", position: "Right" },
    dietary: ["organic", "whole-grain", "high-fiber"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "10",
    name: "Dairy-Free Almond Milk",
    brand: "Silk",
    price: 85,
    category: "Dairy & Eggs",
    description: "Unsweetened almond milk, dairy-free",
    location: { aisle: "B2", shelf: "Cold Storage", position: "Back" },
    dietary: ["dairy-free", "vegan", "low-calorie"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "11",
    name: "Organic Apples",
    brand: "Kashmir Fresh",
    price: 120,
    category: "Fruits & Vegetables",
    description: "Fresh organic red apples",
    location: { aisle: "D1", shelf: "Display", position: "Left" },
    dietary: ["organic", "vegan", "gluten-free"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "12",
    name: "Gluten-Free Oats Bread",
    brand: "Nature's Own",
    price: 75,
    category: "Bakery",
    description: "Gluten-free bread made with oats",
    location: { aisle: "C1", shelf: "Middle", position: "Left" },
    dietary: ["gluten-free", "high-fiber", "dairy-free"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "13",
    name: "Protein Rich Paneer",
    brand: "Amul",
    price: 95,
    category: "Dairy & Eggs",
    description: "Fresh paneer high in protein",
    location: { aisle: "B2", shelf: "Cold Storage", position: "Center" },
    dietary: ["high-protein", "vegetarian"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "14",
    name: "Quinoa Seeds",
    brand: "Organic India",
    price: 320,
    category: "Grains & Cereals",
    description: "Organic quinoa seeds - superfood",
    location: { aisle: "A1", shelf: "Top", position: "Left" },
    dietary: ["organic", "gluten-free", "high-protein", "vegan"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "15",
    name: "Low-Fat Greek Yogurt",
    brand: "Epigamia",
    price: 45,
    category: "Dairy & Eggs",
    description: "Low-fat probiotic Greek yogurt",
    location: { aisle: "B2", shelf: "Cold Storage", position: "Front" },
    dietary: ["low-fat", "high-protein", "probiotic"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "16",
    name: "Organic Tomatoes",
    brand: "Farm Fresh",
    price: 40,
    category: "Fruits & Vegetables",
    description: "Fresh organic tomatoes",
    location: { aisle: "D1", shelf: "Display", position: "Center" },
    dietary: ["organic", "vegan", "gluten-free"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "17",
    name: "Coconut Oil",
    brand: "Parachute",
    price: 120,
    category: "Cooking Oils",
    description: "Pure coconut oil for cooking",
    location: { aisle: "H1", shelf: "Middle", position: "Left" },
    dietary: ["organic", "vegan", "healthy"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "18",
    name: "Atta Whole Wheat Flour",
    brand: "Aashirvaad",
    price: 85,
    category: "Grains & Cereals",
    description: "Premium whole wheat flour",
    location: { aisle: "A1", shelf: "Bottom", position: "Right" },
    dietary: ["whole-grain", "high-fiber"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "19",
    name: "Organic Honey",
    brand: "Dabur",
    price: 195,
    category: "Sweeteners",
    description: "Pure organic honey",
    location: { aisle: "I1", shelf: "Top", position: "Center" },
    dietary: ["organic", "natural"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
  {
    id: "20",
    name: "Brown Rice",
    brand: "Fortune",
    price: 95,
    category: "Grains & Cereals",
    description: "Healthy brown rice",
    location: { aisle: "A1", shelf: "Middle", position: "Left" },
    dietary: ["whole-grain", "gluten-free", "high-fiber"],
    image: "/placeholder.svg?height=100&width=100",
    inStock: true,
  },
]

// Categories available
export const categories = [
  "Fruits & Vegetables",
  "Dairy & Eggs",
  "Grains & Cereals",
  "Pulses & Legumes",
  "Spices & Masalas",
  "Beverages",
  "Bakery",
  "Dry Fruits & Nuts",
  "Cooking Oils",
  "Sweeteners",
]

// Dietary options
export const dietaryOptions = [
  "organic",
  "gluten-free",
  "dairy-free",
  "vegan",
  "vegetarian",
  "high-protein",
  "low-fat",
  "low-calorie",
  "whole-grain",
  "high-fiber",
  "healthy",
  "antioxidant",
  "probiotic",
  "natural",
]
